contact_links:
  - name: Feature Request ğŸ™
    url: https://colorstack-family.slack.com/channels/C06S0DBFD6X
    about: Have a feature idea? Discuss the idea with others in our Slack!
  - name: Ask a Question â“
    url: https://colorstack-family.slack.com/channels/C06S0DBFD6X
    about: Need help on something? Have feedback? Ask in our Slack!
