contact_links:
  - name: Feature Request ğŸš€
    url: https://github.com/colorstackorg/oyster/discussions/new?category=ideas
    about: We use GitHub Discussions to propose and discuss new ideas. ğŸ’¬
  - name: Get Help ğŸ™
    url: https://github.com/colorstackorg/oyster/discussions/new?category=help
    about: Need help on something? Ask a question to other community members!
